export const BANDS = [
  {
    id: "1",
    name: "Children of Bodom",
    country: "Finland",
    countryCode: "FI",
    genres: ["Melodic Death Metal", "Power Metal"],
    matchScore: 99,
    yearFormed: 1993,
    description:
      "Finnish melodic death metal band from Espoo known for neoclassical shredding and extreme intensity.",
    topSongs: [
      { title: "Everytime I Die", duration: "3:24" },
      { title: "Needled 24/7", duration: "4:09" },
      { title: "Are You Dead Yet?", duration: "3:36" },
    ],
    tourDates: [{ venue: "Tuska Festival", city: "Helsinki", date: "2026-06-28" }],
    isFavorite: true,
  },
  {
    id: "2",
    name: "Opeth",
    country: "Sweden",
    countryCode: "SE",
    genres: ["Progressive Metal", "Progressive Rock"],
    matchScore: 95,
    yearFormed: 1990,
    description:
      "Progressive legends from Stockholm blending death metal, acoustic passages, and art-rock ambition.",
    topSongs: [
      { title: "Blackwater Park", duration: "12:07" },
      { title: "Ghost of Perdition", duration: "10:29" },
      { title: "Deliverance", duration: "13:36" },
    ],
    tourDates: [{ venue: "Rockefeller", city: "Oslo", date: "2026-09-15" }],
    isFavorite: true,
  },
  {
    id: "3",
    name: "Mastodon",
    country: "United States",
    countryCode: "US",
    genres: ["Progressive Metal", "Sludge Metal"],
    matchScore: 88,
    yearFormed: 2000,
    description:
      "Atlanta heavyweights with progressive writing, layered riffs, and concept-driven storytelling.",
    topSongs: [
      { title: "Blood and Thunder", duration: "3:49" },
      { title: "Oblivion", duration: "5:41" },
      { title: "The Motherload", duration: "5:18" },
    ],
    tourDates: [{ venue: "The Tabernacle", city: "Atlanta", date: "2026-07-20" }],
    isFavorite: true,
  },
  {
    id: "4",
    name: "Gojira",
    country: "France",
    countryCode: "FR",
    genres: ["Progressive Death Metal", "Groove Metal"],
    matchScore: 92,
    yearFormed: 1996,
    description:
      "French metal powerhouse with environmentally conscious lyrics and technically demanding grooves.",
    topSongs: [
      { title: "Flying Whales", duration: "7:44" },
      { title: "Stranded", duration: "4:28" },
      { title: "Silvera", duration: "3:32" },
    ],
    tourDates: [{ venue: "Zenith", city: "Paris", date: "2026-11-05" }],
    isFavorite: true,
  },
  {
    id: "5",
    name: "Leprous",
    country: "Norway",
    countryCode: "NO",
    genres: ["Progressive Metal", "Art Rock"],
    matchScore: 85,
    yearFormed: 2001,
    description:
      "Norwegian progressive artists moving between heavy rhythmic complexity and atmospheric art rock.",
    topSongs: [
      { title: "The Price", duration: "4:40" },
      { title: "Below", duration: "5:12" },
      { title: "From the Flame", duration: "5:01" },
    ],
    tourDates: [],
  },
  {
    id: "6",
    name: "Jinjer",
    country: "Ukraine",
    countryCode: "UA",
    genres: ["Progressive Metalcore", "Groove Metal"],
    matchScore: 78,
    yearFormed: 2009,
    description:
      "Modern metalcore from Ukraine with dynamic vocals and genre-hopping structures.",
    topSongs: [
      { title: "Pisces", duration: "4:47" },
      { title: "Judgement (& Punishment)", duration: "4:02" },
      { title: "Perennial", duration: "3:38" },
    ],
    tourDates: [{ venue: "Bataclan", city: "Paris", date: "2026-10-12" }],
  },
  {
    id: "7",
    name: "Devin Townsend",
    country: "Canada",
    countryCode: "CA",
    genres: ["Progressive Metal", "Ambient", "Extreme Metal"],
    matchScore: 91,
    yearFormed: 1993,
    description:
      "Genre-defying Canadian composer balancing crushing walls of sound with bright melodic textures.",
    topSongs: [
      { title: "Kingdom", duration: "5:51" },
      { title: "Deadhead", duration: "7:52" },
      { title: "Stormbending", duration: "7:18" },
    ],
    tourDates: [],
  },
  {
    id: "8",
    name: "Alcest",
    country: "France",
    countryCode: "FR",
    genres: ["Blackgaze", "Shoegaze", "Post-Metal"],
    matchScore: 72,
    yearFormed: 2000,
    description:
      "Pioneers of blackgaze, combining shimmering shoegaze textures with black metal intensity.",
    topSongs: [
      { title: "Eclosion", duration: "6:51" },
      { title: "Kodama", duration: "6:22" },
      { title: "Oiseaux de Proie", duration: "5:28" },
    ],
    tourDates: [],
  },
  {
    id: "9",
    name: "Boris",
    country: "Japan",
    countryCode: "JP",
    genres: ["Experimental Rock", "Drone Metal", "Shoegaze"],
    matchScore: 65,
    yearFormed: 1992,
    description:
      "Japanese experimental trio known for shape-shifting across drone, noise, shoegaze, and punk energy.",
    topSongs: [
      { title: "Farewell", duration: "8:24" },
      { title: "Pink", duration: "4:03" },
      { title: "Flood", duration: "18:22" },
    ],
    tourDates: [{ venue: "Shinjuku Loft", city: "Tokyo", date: "2026-08-10" }],
  },
  {
    id: "10",
    name: "Mdou Moctar",
    country: "Niger",
    countryCode: "NE",
    genres: ["Desert Blues", "Psychedelic Rock", "Tuareg Guitar"],
    matchScore: 58,
    yearFormed: 2008,
    description:
      "Tuareg guitar virtuoso fusing desert blues and psychedelic rock with electric urgency.",
    topSongs: [
      { title: "Afrique Victime", duration: "7:46" },
      { title: "Chismiten", duration: "5:12" },
      { title: "Taliat", duration: "6:38" },
    ],
    tourDates: [],
  },
  {
    id: "11",
    name: "King Gizzard",
    country: "Australia",
    countryCode: "AU",
    genres: ["Psychedelic Rock", "Thrash Metal", "Microtonal"],
    matchScore: 74,
    yearFormed: 2010,
    description:
      "Australian collective famous for prolific releases and fearless genre exploration.",
    topSongs: [
      { title: "Mars for the Rich", duration: "4:01" },
      { title: "Robot Stop", duration: "3:06" },
      { title: "The River", duration: "10:15" },
    ],
    tourDates: [{ venue: "Forum Melbourne", city: "Melbourne", date: "2026-12-01" }],
  },
  {
    id: "12",
    name: "Heilung",
    country: "Denmark",
    countryCode: "DK",
    genres: ["Dark Folk", "Ritual Ambient", "Nordic Folk"],
    matchScore: 45,
    yearFormed: 2014,
    description:
      "Ritual collective using ancient instruments and chants to build immersive historical soundscapes.",
    topSongs: [
      { title: "Krigsgaldr", duration: "8:43" },
      { title: "Norupo", duration: "7:14" },
      { title: "Anoana", duration: "5:59" },
    ],
    tourDates: [],
  },
  {
    id: "13",
    name: "Igorrr",
    country: "France",
    countryCode: "FR",
    genres: ["Breakcore", "Baroque", "Death Metal"],
    matchScore: 68,
    yearFormed: 2005,
    description:
      "Unclassifiable fusion of breakcore chaos, baroque harmony, and extreme metal velocity.",
    topSongs: [
      { title: "Very Noise", duration: "3:35" },
      { title: "Parpaing", duration: "4:20" },
      { title: "Cheval", duration: "5:11" },
    ],
    tourDates: [],
  },
  {
    id: "14",
    name: "Tinariwen",
    country: "Mali",
    countryCode: "ML",
    genres: ["Desert Blues", "Tuareg Rock"],
    matchScore: 42,
    yearFormed: 1979,
    description:
      "Grammy-winning pioneers of desert blues blending Saharan guitar traditions with rock rhythms.",
    topSongs: [
      { title: "Chet Boghassa", duration: "5:41" },
      { title: "Sastanara", duration: "4:56" },
      { title: "Nannuflay", duration: "3:58" },
    ],
    tourDates: [],
  },
  {
    id: "15",
    name: "Haken",
    country: "United Kingdom",
    countryCode: "GB",
    genres: ["Progressive Metal", "Djent"],
    matchScore: 87,
    yearFormed: 2007,
    description:
      "British prog unit combining technical precision, cinematic storytelling, and modern heaviness.",
    topSongs: [
      { title: "Cockroach King", duration: "8:35" },
      { title: "Messiah Complex", duration: "19:42" },
      { title: "Puzzle Box", duration: "4:46" },
    ],
    tourDates: [{ venue: "Electric Ballroom", city: "London", date: "2026-05-18" }],
  },
  {
    id: "16",
    name: "Soen",
    country: "Sweden",
    countryCode: "SE",
    genres: ["Progressive Metal", "Alternative Metal"],
    matchScore: 83,
    yearFormed: 2010,
    description:
      "Swedish progressive project bridging groove-heavy riffs and emotional atmospheric songwriting.",
    topSongs: [
      { title: "Lotus", duration: "4:43" },
      { title: "Martyrs", duration: "4:48" },
      { title: "Antagonist", duration: "5:08" },
    ],
    tourDates: [],
  },
  {
    id: "17",
    name: "Periphery",
    country: "United States",
    countryCode: "US",
    genres: ["Djent", "Progressive Metalcore"],
    matchScore: 76,
    yearFormed: 2005,
    description:
      "Djent innovators with polyrhythmic riffing and expansive melodic arrangements.",
    topSongs: [
      { title: "Marigold", duration: "9:30" },
      { title: "Scarlet", duration: "5:38" },
      { title: "Lune", duration: "8:22" },
    ],
    tourDates: [],
  },
  {
    id: "18",
    name: "Wardruna",
    country: "Norway",
    countryCode: "NO",
    genres: ["Nordic Folk", "Dark Ambient"],
    matchScore: 52,
    yearFormed: 2003,
    description:
      "Nordic ensemble building cinematic ritual music from old Norse instruments and traditions.",
    topSongs: [
      { title: "Helvegen", duration: "5:55" },
      { title: "Lyfjaberg", duration: "7:03" },
      { title: "Gronnansen", duration: "6:49" },
    ],
    tourDates: [],
  },
  {
    id: "19",
    name: "Myrkur",
    country: "Denmark",
    countryCode: "DK",
    genres: ["Black Metal", "Nordic Folk", "Dream Pop"],
    matchScore: 70,
    yearFormed: 2014,
    description:
      "Danish project mixing atmospheric black metal with folk instrumentation and dreamlike melodies.",
    topSongs: [
      { title: "Ulvinde", duration: "5:11" },
      { title: "Juniper", duration: "3:52" },
      { title: "Onde Born", duration: "4:03" },
    ],
    tourDates: [],
  },
  {
    id: "20",
    name: "Khruangbin",
    country: "United States",
    countryCode: "US",
    genres: ["Psychedelic Soul", "Funk", "World Music"],
    matchScore: 35,
    yearFormed: 2010,
    description:
      "Global funk trio from Texas with groove-heavy, transportive instrumentals and minimalist songwriting.",
    topSongs: [
      { title: "People Everywhere", duration: "3:47" },
      { title: "Time (You and I)", duration: "4:03" },
      { title: "Evan Finds the Third Room", duration: "3:51" },
    ],
    tourDates: [],
  },
];

export const USER_PROFILE = {
  name: "Ben",
  username: "Ben",
  favoriteGenres: [
    "Progressive Metal",
    "Death Metal",
    "Grunge",
    "Nu Metal",
    "Power Metal",
    "Heavy Metal",
  ],
  favoriteBandIds: ["1", "2", "3", "4"],
};

export const ALL_GENRES = [
  "Progressive Metal",
  "Death Metal",
  "Melodic Death Metal",
  "Power Metal",
  "Grunge",
  "Nu Metal",
  "Heavy Metal",
  "Thrash Metal",
  "Black Metal",
  "Sludge Metal",
  "Groove Metal",
  "Djent",
  "Progressive Metalcore",
  "Progressive Rock",
  "Art Rock",
  "Psychedelic Rock",
  "Experimental Rock",
  "Shoegaze",
  "Post-Metal",
  "Blackgaze",
  "Desert Blues",
  "Dark Folk",
  "Nordic Folk",
  "Breakcore",
  "Baroque",
  "Ambient",
  "Dream Pop",
  "Psychedelic Soul",
  "Funk",
  "World Music",
  "Tuareg Guitar",
  "Drone Metal",
  "Microtonal",
  "Ritual Ambient",
  "Alternative Metal",
  "Dark Ambient",
];
